---

- hosts: all
  become: true
  roles:
    - base
  tasks:

  - name: install apache2
    dnf:
      name: httpd

  - name: start httpd apache
    service: 
      name: httpd
      state: started

  - name: add ssh key to yeeet
    tags: always
    authorized_key:
      user: yeeet
      key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIDAiX3mNQfr0stG6APHMC/6VuG/W1rBcH3DQqu2Irt0r ansible"
  
