- name: install apache2
  dnf:
    name: "{{ apache_package_name }}"

- name: start httpd apache
  service: 
    name: "{{ apache_service }}"
    state: started
    enabled: yes 

- name: copy html file 
  copy: 
    src: site.html
    dest: /var/www/html/index.html
    owner: root
    group: root
    mode: 0644


